In [ ]:
import pandas as pd
list_buah = ['jeruk','pepaya','mangga','rambutan','leci','nanas','manggis']

#membuat dataframe menggunakan list buah
df = pd.DataFrame(list_buah)
df

0
0     jeruk
1    pepaya
2    mangga
3  rambutan
4      leci
5     nanas
6   manggis

In [ ]:
#membuat data frame menggunakan list dan fungsi zip
list_buah = ['jeruk','pepaya','mangga','rambutan','leci','nanas','manggis']
list_berat = [50,800,150,10,2,300,70]

df = pd.DataFrame(list(zip(list_buah, list_berat)), 
                  columns = ['Nama Buah', 'Berat Buah'])
df


Nama Buah  Berat Buah
0     jeruk          50
1    pepaya         800
2    mangga         150
3  rambutan          10
4      leci           2
5     nanas         300
6   manggis          70

In [ ]:
#Membuat DataFrame menggunakan multidimensi
list = [['bejo', 25], ['Ari',30], ['Asep', 26],['richard', 22]]

df = pd.DataFrame(list, columns = ['Nama','Usia'])
df

Nama  Usia
0     bejo    25
1      Ari    30
2     Asep    26
3  richard    22

In [ ]:
#membuat DataFrame menggunakan dictionary
mobil = {'Type Mobil': ['Honda Civic','Toyota Corolla', 'Ford Focus','Audi A4'],
        'Harga(juta)' : [22,25,27,32]}

df = pd.DataFrame(mobil)
df

Type Mobil  Harga(juta)
0     Honda Civic           22
1  Toyota Corolla           25
2      Ford Focus           27
3         Audi A4           32

In [ ]:
df_super_store = pd.read_csv('/Super-Store-Dataset.csv')
df_super_store

order_id  order_date customer_id    segment         category  \
0     CA-2016-152156   11/8/2016    CG-12520   Consumer        Furniture   
1     CA-2016-152156   11/8/2016    CG-12520   Consumer        Furniture   
2     CA-2016-138688   6/12/2016    DV-13045  Corporate  Office Supplies   
3     US-2015-108966  10/11/2015    SO-20335   Consumer        Furniture   
4     US-2015-108966  10/11/2015    SO-20335   Consumer  Office Supplies   
...              ...         ...         ...        ...              ...   
9983  CA-2014-110422   1/21/2014    TB-21400   Consumer        Furniture   
9984  CA-2017-121258   2/26/2017    DB-13060   Consumer        Furniture   
9985  CA-2017-121258   2/26/2017    DB-13060   Consumer       Technology   
9986  CA-2017-121258   2/26/2017    DB-13060   Consumer  Office Supplies   
9987  CA-2017-119914    5/4/2017    CC-12220   Consumer  Office Supplies   

     sub_category     sales  quantity    profit  
0       Bookcases  261.9600         2   41.9136  
1          Chairs  731.9400         3  219.5820  
2          Labels   14.6200         2    6.8714  
3          Tables  957.5775         5 -383.0310  
4         Storage   22.3680         2    2.5164  
...           ...       ...       ...       ...  
9983  Furnishings   25.2480         3    4.1028  
9984  Furnishings   91.9600         2   15.6332  
9985       Phones  258.5760         2   19.3932  
9986        Paper   29.6000         4   13.3200  
9987   Appliances  243.1600         2   72.9480  

[9988 rows x 9 columns]

In [ ]:
df_data = pd.read.excel('/datasetpilkadadki.xlsx')
df_data

AttributeError: ignored

#NUMPY

In [ ]:
import numpy as np
list_1 = [1,2,3,4,5]
arr_1 = np.array([list_1])
arr_1

array([[1, 2, 3, 4, 5]])

In [ ]:
#membuat array dengan nilai 0 shape(5,5)
print(np.zeros((2,5)))

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [ ]:
#membuat array dengan nilai 1 shape(5,5)
print(np.ones((5,3)))

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
#arrange(start, stop, step(loncat))
print(np.arange(1,10,2))

[1 3 5 7 9]


In [ ]:
#linespace(start, stop, number)
print(np.linspace(1,10,4))

[ 1.  4.  7. 10.]


In [ ]:
#logspace(start,stop,number)
print(np.logspace(1,10,2))

[1.e+01 1.e+10]


In [ ]:
#membuat array matriks dengan shape(2,2) dengan elemen 99
print(np.full((2,2), 4))

[[4 4]
 [4 4]]


In [ ]:
A = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(A)

print(np.full_like(A,3))   #membuat matriks dengan shape yang sama dengan A dg semua elemen 

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]
[[3 3 3 3 3 3 3]
 [3 3 3 3 3 3 3]]


In [ ]:
#random decimal numbers
print(np.random.rand(4,2))

[[0.80675854 0.18558545]
 [0.06726279 0.36010242]
 [0.49064528 0.47909108]
 [0.02486321 0.43357212]]


In [ ]:
#random integer values
print(np.random.randint(-4,8, size =(3,3)))    #batas -4 sampai 8, dengan ukuran matriks 3x3

[[ 3 -3 -1]
 [ 1  3  3]
 [ 1  0 -1]]


In [ ]:
#membuat matriks identitas
print(np.identity(5))

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [ ]:
arr = np.array([[1,2,3]])  #membuat matriks dengan perulangan matriks
r1 = np.repeat(arr,3, axis = 0)  #axis 0 untuk kolom, axis 1 untuk baris
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [ ]:
a = np.array([29, 28, 30], dtype = 'int32')
print(a)

print('Dimensi dari array a adalah :', a.ndim)

[29 28 30]
Dimensi dari array a adalah : 1
